# Generated by Django 6.1.1 on 2026-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getschema', '0002_alter_schema_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='api_version',
            field=models.TextField(blank=True),
        ),
    ]
