# Generated by Django 6.1.1 on 2026-09-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getschema', '0003_schema_api_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='include_field_description',
            field=models.BooleanField(default=False),
        ),
    ]
