[project]
name = "schemalister"
version = "0.1.0"
description = "This tool uses the Salesforce Metadata API to build a list of objects, fields and field attributes from within your Salesforce Org."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery>=5.6.3",
    "cryptography==50.0.1",
    "django==6.1.1",
    "django-celery-beat>=2.1.0",
    "django-environ",
    "gunicorn>=26.2.0",
    "pyjwt>=2.13.0",
    "python-dotenv==1.2.3",
    "redis==8.1.0",
    "requests==2.34.2",
    "whitenoise>=6.12.0",
    "xlsxwriter==3.2.9",
]
